spring:
  profiles:
    active: dev
  #时间戳统一转换
  data:
    # 关闭spring data 的redis仓库
    redis:
      repositories:
        enabled: false

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  time-zone: GMT+8

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-m5ee476bu350735gjeo.mysql.rds.aliyuncs.com:3306/first_smart_campus?useUnide=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2b8
    username: root
    password: XuNiit_#

    hikari:
      minimum-idle: 1
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 10000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    database: mysql
    show-sql: false
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  redis:
    database: 0
    host: 101.37.31.188
    port: 6379
    password:
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        min-idle: 0
    timeout: 1000


# mybatis-Plus配置
mybatis-plus:
  configuration:
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    jdbc-type-for-null: 'null'
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.team2.smartcampus.entity
  global-config:
    db-config:
      #主键类型：auto主键自增，input用户输入id，id_worker全局唯一数字id，UUID全局唯一的UUID
      id-type: auto
      #字段策略
      field-strategy: not_empty
      #开启驼峰是命名
      table-underline: true

qq:
  # ntt
  oauth:
    http: http://www.ntt1914866205.xyz